### ISSUE TITLE
Job Training (Lalonde 1986) is missing

### ISSUE THREAD

**Issue by TwsThomas** [rguo12/awesome-causality-data#3]
Hello, 

Thank you for this rich review!
Job Training (Lalonde 1986) is missing (dead link)

We can found it in the R package 'qte'
(https://rdrr.io/cran/qte/man/lalonde.html#heading-0)

**Comment by rguo12** [comment]
> Hello,
> 
> Thank you for this rich review!
> Job Training (Lalonde 1986) is missing (dead link)
> 
> We can found it in the R package 'qte'
> (https://rdrr.io/cran/qte/man/lalonde.html#heading-0)

Great suggestion! I will add the link you provided!

**Comment by rguo12** [comment]
I will close the issue as the link to Lalonde 1986 is added.
